version: '3.9'

services:
  mysql:
    container_name: go-crm-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shopdevgo
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    container_name: go-crm-redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  go-crm:
    container_name: go-crm-backend-shopdev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis

volumes:
  mysql-data:
  redis-data:

networks:
  go-crm-network: